/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check process health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check dependency readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's sandboxes */
        get: operations["listSandboxes"];
        put?: never;
        /**
         * Request a temporary computer
         * @description Creates a sandbox asynchronously. Supplying the same Idempotency-Key
         *     for the same owner returns the original sandbox instead of creating a
         *     second computer.
         */
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        /** Get a sandbox */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        /**
         * Destroy a sandbox
         * @description Destroy is idempotent. A sandbox already in destroyed state is a successful no-op.
         */
        delete: operations["destroySandbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a command in a running sandbox */
        post: operations["executeCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/commands/{commandId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
                commandId: components["parameters"]["CommandID"];
            };
            cookie?: never;
        };
        /** Get command status and result */
        get: operations["getCommand"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/commands/{commandId}/events": {
        parameters: {
            query?: never;
            header?: {
                /** @description Last SSE sequence received by the caller for replay. */
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path: {
                sandboxId: components["parameters"]["SandboxID"];
                commandId: components["parameters"]["CommandID"];
            };
            cookie?: never;
        };
        /**
         * Stream ordered command events
         * @description Returns replayable Server-Sent Events. Each frame has an id, event,
         *     and JSON data field. Last-Event-ID resumes from the last delivered
         *     sequence while the command record is retained. The terminal completed
         *     or failed event closes the stream.
         */
        get: operations["streamCommandEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/files": {
        parameters: {
            query?: {
                /** @description Absolute path beneath `/workspace`; defaults to `/workspace`. */
                path?: components["parameters"]["WorkspacePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        /** List workspace entries */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/files/content": {
        parameters: {
            query: {
                /** @description Absolute file path beneath `/workspace`. */
                path: components["parameters"]["FilePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        /** Read workspace file content */
        get: operations["readFile"];
        /** Write workspace file content */
        put: operations["writeFile"];
        post?: never;
        /** Delete a workspace file or empty directory */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        /** List snapshots for a sandbox */
        get: operations["listSnapshots"];
        put?: never;
        /**
         * Snapshot the workspace
         * @description Supplying the same Idempotency-Key returns the original snapshot instead of creating a second archive.
         */
        post: operations["createSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/snapshots/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: components["parameters"]["SnapshotID"];
            };
            cookie?: never;
        };
        /** Get snapshot metadata */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandboxes/{sandboxId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a snapshot into a stopped sandbox */
        post: operations["restoreSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SandboxState: "requested" | "provisioning" | "starting" | "running" | "snapshotting" | "stopping" | "stopped" | "failed" | "destroyed";
        /**
         * @description Opaque sandbox identifier.
         * @example sbx_01HZY
         */
        SandboxID: string;
        /**
         * @description Opaque command identifier.
         * @example cmd_01HZX
         */
        CommandID: string;
        /**
         * @description Opaque snapshot identifier.
         * @example snp_01HZW
         */
        SnapshotID: string;
        /** @example req_01HZZ */
        RequestID: string;
        /**
         * Format: date-time
         * @description RFC 3339 timestamp with an explicit timezone.
         */
        Timestamp: string;
        /** @default /workspace */
        WorkspacePath: string;
        WorkspaceFilePath: string;
        RepositoryConfig: {
            /** @enum {string} */
            provider: "github";
            /** Format: uri */
            url: string;
            ref?: string;
            path: components["schemas"]["WorkspacePath"];
        };
        SandboxConfig: {
            image: string;
            cpuMillis: number;
            memoryMiB: number;
            storageGiB: number;
            maxLifetimeSeconds: number;
            defaultCommandTimeoutSeconds: number;
            environment: {
                [key: string]: string;
            };
            repository?: components["schemas"]["RepositoryConfig"];
            snapshotId?: components["schemas"]["SnapshotID"];
        };
        SandboxCreateRequest: {
            config: components["schemas"]["SandboxConfig"];
        };
        Sandbox: {
            id: components["schemas"]["SandboxID"];
            state: components["schemas"]["SandboxState"];
            repository?: components["schemas"]["RepositoryConfig"];
            config: components["schemas"]["SandboxConfig"];
            createdAt: components["schemas"]["Timestamp"];
            expiresAt: components["schemas"]["Timestamp"];
            lastActivityAt: components["schemas"]["Timestamp"];
            currentCommandId?: components["schemas"]["CommandID"];
            snapshotIds: components["schemas"]["SnapshotID"][];
        };
        CommandRequest: {
            command: string;
            cwd?: components["schemas"]["WorkspacePath"];
            environment?: {
                [key: string]: string;
            };
            timeoutSeconds?: number;
        };
        CommandResult: {
            id: components["schemas"]["CommandID"];
            sandboxId: components["schemas"]["SandboxID"];
            command: string;
            exitCode: number | null;
            startedAt: components["schemas"]["Timestamp"];
            finishedAt?: components["schemas"]["Timestamp"];
            timedOut: boolean;
            signal?: string;
        };
        CommandEvent: components["schemas"]["CommandStartedEvent"] | components["schemas"]["CommandOutputEvent"] | components["schemas"]["CommandCompletedEvent"] | components["schemas"]["CommandFailedEvent"];
        CommandStartedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CommandStartedEvent";
            commandId: components["schemas"]["CommandID"];
            at: components["schemas"]["Timestamp"];
        };
        CommandOutputEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CommandOutputEvent";
            commandId: components["schemas"]["CommandID"];
            data: string;
            at: components["schemas"]["Timestamp"];
        };
        CommandCompletedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CommandCompletedEvent";
            commandId: components["schemas"]["CommandID"];
            result: components["schemas"]["CommandResult"];
            at: components["schemas"]["Timestamp"];
        };
        CommandFailedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CommandFailedEvent";
            commandId: components["schemas"]["CommandID"];
            code: string;
            message: string;
            at: components["schemas"]["Timestamp"];
        };
        FileEntry: {
            path: components["schemas"]["WorkspaceFilePath"];
            /** @enum {string} */
            kind: "file" | "directory" | "symlink";
            byteSize?: number;
            modifiedAt?: components["schemas"]["Timestamp"];
        };
        FileListResponse: {
            path: components["schemas"]["WorkspacePath"];
            entries: components["schemas"]["FileEntry"][];
        };
        SnapshotCreateRequest: {
            expiresAt?: components["schemas"]["Timestamp"];
        };
        SnapshotMetadata: {
            id: components["schemas"]["SnapshotID"];
            sandboxId: components["schemas"]["SandboxID"];
            /** @enum {string} */
            state: "requested" | "creating" | "available" | "failed" | "deleted";
            /** @description Opaque archive reference; not an S3 URL. */
            objectKey: string;
            byteSize?: number;
            checksum?: string;
            createdAt: components["schemas"]["Timestamp"];
            expiresAt?: components["schemas"]["Timestamp"];
        };
        RestoreRequest: {
            snapshotId: components["schemas"]["SnapshotID"];
        };
        PageInfo: {
            nextCursor?: string;
            hasMore: boolean;
        };
        SandboxPage: {
            items: components["schemas"]["Sandbox"][];
            page: components["schemas"]["PageInfo"];
        };
        SnapshotPage: {
            items: components["schemas"]["SnapshotMetadata"][];
            page: components["schemas"]["PageInfo"];
        };
        ApiError: {
            /** @example sandbox_not_running */
            code: string;
            message: string;
            requestId: components["schemas"]["RequestID"];
            details: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "ready";
            version: string;
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description API key missing or invalid. */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "authentication_required",
                 *         "message": "A valid API key is required.",
                 *         "requestId": "req_01HZZ",
                 *         "details": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource state or idempotency conflict. */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Command, environment, or file body exceeds the configured limit. */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "payload_too_large",
                 *         "message": "File body exceeds the 10485760 byte limit.",
                 *         "requestId": "req_01HZZ",
                 *         "details": {
                 *           "maxBytes": 10485760
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Command exceeded its server-side timeout. */
        CommandTimeout: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "command_timeout",
                 *         "message": "Command exceeded its timeout.",
                 *         "requestId": "req_01HZZ",
                 *         "details": {
                 *           "commandId": "cmd_01HZX",
                 *           "timeoutSeconds": 30
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the caller may retry. */
                "Retry-After"?: number;
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service is not ready. */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SandboxID: components["schemas"]["SandboxID"];
        CommandID: components["schemas"]["CommandID"];
        SnapshotID: components["schemas"]["SnapshotID"];
        /** @description Opaque cursor returned by a previous page. */
        Cursor: string;
        /** @description Maximum number of resources to return. */
        Limit: number;
        /** @description Caller-generated key retained for safe retries of create operations. */
        IdempotencyKey: string;
        /** @description Last SSE sequence received by the caller for replay. */
        LastEventID: string;
        /** @description Absolute path beneath `/workspace`; defaults to `/workspace`. */
        WorkspacePath: components["schemas"]["WorkspacePath"];
        /** @description Absolute file path beneath `/workspace`. */
        FilePath: components["schemas"]["WorkspaceFilePath"];
    };
    requestBodies: never;
    headers: {
        /** @description Request identifier for support and log correlation. */
        RequestID: string;
        /** @description URL of the accepted resource. */
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is healthy. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The control plane is ready to accept requests. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listSandboxes: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by a previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of resources to return. */
                limit?: components["parameters"]["Limit"];
                /** @description Filter by lifecycle state. */
                state?: components["schemas"]["SandboxState"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of sandboxes. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key retained for safe retries of create operations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxCreateRequest"];
            };
        };
        responses: {
            /** @description Sandbox creation accepted. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sandbox details. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    destroySandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destruction accepted or already complete. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    executeCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Command accepted for execution. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
                commandId: components["parameters"]["CommandID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command status. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            408: components["responses"]["CommandTimeout"];
        };
    };
    streamCommandEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Last SSE sequence received by the caller for replay. */
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path: {
                sandboxId: components["parameters"]["SandboxID"];
                commandId: components["parameters"]["CommandID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered command event stream. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listFiles: {
        parameters: {
            query?: {
                /** @description Absolute path beneath `/workspace`; defaults to `/workspace`. */
                path?: components["parameters"]["WorkspacePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace entries below the requested path. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    readFile: {
        parameters: {
            query: {
                /** @description Absolute file path beneath `/workspace`. */
                path: components["parameters"]["FilePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File bytes. */
            200: {
                headers: {
                    /** @description Opaque content version for conditional requests. */
                    ETag?: string;
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    writeFile: {
        parameters: {
            query: {
                /** @description Absolute file path beneath `/workspace`. */
                path: components["parameters"]["FilePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description File written. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    deleteFile: {
        parameters: {
            query: {
                /** @description Absolute file path beneath `/workspace`. */
                path: components["parameters"]["FilePath"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted. */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSnapshots: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by a previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum number of resources to return. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of snapshots. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createSnapshot: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated key retained for safe retries of create operations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SnapshotCreateRequest"];
            };
        };
        responses: {
            /** @description Snapshot creation accepted. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotMetadata"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshotId: components["parameters"]["SnapshotID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot metadata. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotMetadata"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    restoreSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sandboxId: components["parameters"]["SandboxID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Restore accepted. */
            202: {
                headers: {
                    Location: components["headers"]["Location"];
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sandbox"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
